# Úloha č.1
- Knihovny a moduly pro matematické výpočty

## Knihovny

In [37]:
import math
import time
import numpy as np
import scipy.integrate as integrate

## Factorial

In [38]:
# Python
start_p = time.time()
x = 951
result = 1

for i in range(1, x):
    result = result * i 
end_p = time.time()
result = str(result)

print(f"Python: {result[:5]}" )
print(f"Čas: {(end_p - start_p)}\n")

# Knihovna
result = 0
start_k = time.time()
result = math.factorial(951)
end_k = time.time()
result = str(result)

print(f"Math: {result[:5]}")
print(f"Čas: {(end_k - start_k)}")
print(f"Rozdíl: {(end_k - start_k) - (end_p - start_p)}")

Python: 13984
Čas: 0.0030405521392822266

Math: 13299
Čas: 0.0
Rozdíl: -0.0030405521392822266


## Integrál

In [39]:
# Python
def f(x):
    return (x**2 - x + 4) / 4

start_p = time.time()

result = 0.0
x = 0
b = 3
dx = 0.0001

while x < b:
    result += dx * (f(x) + f(x + dx)) / 2
    x += dx

end_p = time.time()

print(f"Python: {result}")
print(f"Čas: {(end_p - start_p)}")

# Knihovna
start_k = time.time()
result, error = integrate.quad(lambda x: (x**2 - x + 4) / 4, 0, 3)
end_k = time.time()

print(f"Scipy: {result}")
print(f"Čas: {(end_k - start_k)}")

print(f"Rozdíl: {(end_k - start_k) - (end_p - start_p)}")

Python: 4.125000001250848
Čas: 0.057286977767944336
Scipy: 4.125
Čas: 0.0
Rozdíl: -0.057286977767944336


## Soustava lineárních rovnic

In [40]:
# Python
def jacob_method(A, b, x0=None, tolerance=1e-10, max_iterations=1000):
    n = len(A)
    if x0 is None:
        x0 = np.zeros(n)
    x = x0.copy()
    x_new = x0.copy()

    for iteration in range(max_iterations):
        for i in range(n):
            sum_Ax = sum(A[i][j] * x[j] for j in range(n) if j != i)
            x_new[i] = (b[i] - sum_Ax) / A[i][i]
        if np.allclose(x, x_new, atol=tolerance):
            return x_new

        x = x_new.copy()

    raise ValueError("Jacobi method did not converge within the maximum number of iterations")

A = np.array([
    [10, -1,  2, 0, 0],
    [-1, 11, -1, 3, 0],
    [ 2, -1, 10, -1, 0],
    [ 0,  3, -1, 8, -1],
    [ 0,  0,  0, -1, 5]
])
b = np.array([6, 25, -11, 15, 10])
x0 = np.zeros(len(b))

start_p = time.time()
result_python = jacob_method(A, b, x0)
end_p = time.time()

print("Python:")
for i, x_i in enumerate(result_python):
    print(f"x{i} = {x_i:.6f}")
print(f"Čas: {(end_p - start_p)}\n")

#Knihovna
start_k = time.time()
result_scipy = np.linalg.solve(A, b)
end_k = time.time()

print("Numpy:")
for i, x_i in enumerate(result_scipy):
    print(f"x{i} = {x_i:.6f}")

print("Čás:", end_k - start_k)
print("Rozdíl:", (end_k - start_k) - (end_p - start_p))

Python:
x0 = 0.986226
x1 = 1.914287
x2 = -0.973979
x3 = 1.318350
x4 = 2.263672
Čas: 0.0015819072723388672

Numpy:
x0 = 0.986225
x1 = 1.914290
x2 = -0.973981
x3 = 1.318353
x4 = 2.263671
Čás: 0.0
Rozdíl: -0.0015819072723388672


## Nasobení matic

In [41]:
# Python
start_p = time.time()

result = [[11, 425, 226], [35, 575, 12], [25, 135, 32]]

for i in range(len(result)):
    for j in range(len(result[0])):
        result[i][j] = result[i][j]*25

end_p = time.time()

print(f"Python: {result}")
print(f"Čas: {(end_p - start_p)}\n")

# Knihovna
matrix = [[11, 425, 226], [35, 575, 12], [25, 135, 32]]
start_k = time.time()
result = np.array(matrix)*25
end_k = time.time()

print(f"Numpy:\n {result}")
print(f"Čas: {(end_k - start_k)}")
print(f"Rozdíl: {(end_k - start_k) - (end_p - start_p)}")

Python: [[275, 10625, 5650], [875, 14375, 300], [625, 3375, 800]]
Čas: 0.0

Numpy:
 [[  275 10625  5650]
 [  875 14375   300]
 [  625  3375   800]]
Čas: 0.0
Rozdíl: 0.0


## Skalární Součin

In [42]:
# Python
start_p = time.time()

result = 0
a = (4, 8, 5)
b = (7, 5, 5)

for i in range(len(a)):
    result += a[i]*b[i]

end_p = time.time()
print(f"Python: {result}")
print(f"Čas: {(end_p - start_p)}\n")

# Knihovna
start_k = time.time()

a = np.array([4, 8, 5])
b = np.array([7, 5, 5])

result = sum(a*b)

end_k = time.time()
print(f"Numpy: {result}")
print(f"Čas: {(end_k - start_k)}")
print(f"Rozdíl : {(end_k - start_k) - (end_p - start_p)}")

Python: 93
Čas: 0.0

Numpy: 93
Čas: 0.0
Rozdíl : 0.0
